services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interview_db
    ports:
      - "5432:5432"
    volumes: 
      - postgres_interview_db_data:/var/lib/postgresql

  postgresql_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interview_db_test
    ports:
      - "5433:5432"
    volumes: 
      - postgres_interview_db_test_data:/var/lib/postgresql

volumes:
  postgres_interview_db_data:
  postgres_interview_db_test_data: